### ISSUE TITLE
网关问题

### ISSUE THREAD

**Issue by leenchan** [aa65535/openwrt-redsocks2#10]
redsocks2 运行在 网关192.168.1.1上，
192.168.1.2等 客户端 正常
192.168.1.1 不能 wget qiang外的东西， redsocks2的log 没有显示192.168.1.1的log
请问 192.168.1.1 数据怎么才能通过 redsocks2？

**Comment by aa65535** [comment]
因为没有将规则应用到 OUTPUT chain，所以不支持你所说的功能。

```shell
iptables -t nat -A OUTPUT -p tcp -j REDSOCKS2
```
