### ISSUE TITLE
编译问题

### ISSUE THREAD

**Issue by Eveink** [aa65535/openwrt-redsocks2#15]
In file included from parser.c:29:0:
utils.h:6:19: fatal error: event.h: No such file or directory
compilation terminated.
使用的SDK
OpenWrt-SDK-mvebu_gcc-5.3.0_musl-1.1.15_eabi.Linux-x86_64
SDK里头没有event.h这个头文件。。

**Comment by aa65535** [comment]
`apt-get install libevent-dev`

**Comment by Eveink** [comment]
编译的主机有装这个包的。主机include目录里也有这个头文件。 不明情况，要不请你发布mvebu预编译ipk吧，我赞助10块 - -

**Comment by aa65535** [comment]
@Eveink http://sourceforge.net/projects/openwrt-dist/files/redsocks2/0.60-04dd685/

**Comment by Eveink** [comment]
刚装上发现运行不了，op trunk版本的libc用的musl你编译用的工具链还是uClibc的。
btw 支付宝上的aa65535@live.com是你吧？

**Comment by aa65535** [comment]
@Eveink 目前编译的版本是基于 uClibc 的.
编译除问题的话，去找个对应的库的 Makefile 放到 package 里就行了。
https://github.com/openwrt/openwrt/tree/master/package/libs/libevent2

如果发现缺少以下错误
```
missing dependencies for the following libraries:
libc.so
libgcc_s.so.1
```
可以 install feeds
```
./scripts/feeds update -a
./scripts/feeds install -a
```
然后再重新编译

提供 musl libc 下编译的版本

[redsocks2_0.60-2_mvebu.ipk.zip](https://github.com/aa65535/openwrt-redsocks2/files/442433/redsocks2_0.60-2_mvebu.ipk.zip)
