### ISSUE TITLE
增加libopenssl依赖

### ISSUE THREAD

**Issue by wongsyrone** [aa65535/openwrt-redsocks2#4]
redsocks2 中 commit 0971e57e3928521839652cd396a63a913e5b0eda 编译提示缺少 libcrypto.so.1.0.0 和 libssl.so.1.0.0.

redsocks2默认使用openssl库，增加 libopenssl 依赖之后问题解决

**Comment by aa65535** [comment]
目前 semigodking/redsocks@0971e57 尚未 releases
