### ISSUE TITLE
开机启动顺序问题

### ISSUE THREAD

**Issue by unitone** [aa65535/openwrt-redsocks2#9]
WNDR4300官方固件，redsocks2的启动顺序是90，而shadowsocks-libev的是95。这样的顺序，重新开路由，redsocks2代理无法使用，需要重新启动redsocks2才能成功。目前解决方法是把它们的启动顺序互换。

**Comment by aa65535** [comment]
shadowsocks-libev-spec 是 90
shadowsocks-libev 是 95

**Comment by unitone** [comment]
不好意思，弄错了，应该是shadowsocks-libev和redsocks2的组合有问题，redsocks2开机比shadowsocks快了。导致代理失败。
